//CONFIG ACTIONS
export const RESET_CONFIG_STATE: string = "RESET_CONFIG_STATE";
export const CERTIFIER_LOGIN: string = "CERTIFIER_LOGIN";
export const CLIENT_LOGIN: string = "CLIENT_LOGIN";

//NFT ACTIONS
export const SET_NFT_STATE: string = "SET_NFT_STATE";
export const RESET_NFT_STATE: string = "RESET_NFT_STATE";

export const FETCH_NFT_REQUEST: string = "FETCH_NFT_REQUEST";
export const FETCH_NFT_SUCCESS: string = "FETCH_NFT_SUCCESS";
export const NFT_FAILURE: string = "NFT_FAILURE";

export const FETCH_ALL_NFTS_REQUEST: string = "FETCH_ALL_NFTS_REQUEST";
export const FETCH_ALL_NFTS_SUCCESS: string = "FETCH_ALL_NFTS_SUCCESS";

export const FETCH_AVAILABLE_NFTS_REQUEST: string =
  "FETCH_AVAILABLE_NFTS_REQUEST";
export const FETCH_AVAILABLE_NFTS_SUCCESS: string =
  "FETCH_AVAILABLE_NFTS_SUCCESS";

export const CREATE_NFT_REQUEST: string = "CREATE_NFT_REQUEST";
export const CREATE_NFT_SUCCESS: string = "CREATE_NFT_SUCCESS";

//CERTIFICATION ACTIONS
export const SET_CERTIFICATION_STATE: string = "SET_CERTIFICATION_STATE";
export const RESET_CERTIFICATION_STATE: string = "RESET_CERTIFICATION_STATE";

export const FETCH_CERTIFICATION_REQUEST: string =
  "FETCH_CERTIFICATION_REQUEST";
export const FETCH_CERTIFICATION_SUCCESS: string =
  "FETCH_CERTIFICATION_SUCCESS";
export const CERTIFICATION_FAILURE: string = "CERTIFICATION_FAILURE";

export const FETCH_ALL_CERTIFICATIONS_REQUEST: string =
  "FETCH_ALL_CERTIFICATIONS_REQUEST";
export const FETCH_ALL_CERTIFICATIONS_SUCCESS: string =
  "FETCH_ALL_CERTIFICATIONS_SUCCESS";

export const FETCH_CERTIFICATIONS_BY_ADDRESS_REQUEST: string =
  "FETCH_CERTIFICATIONS_BY_ADDRESS_REQUEST";
export const FETCH_CERTIFICATIONS_BY_ADDRESS_SUCCESS: string =
  "FETCH_CERTIFICATIONS_BY_ADDRESS_SUCCESS";

export const CREATE_CERTIFICATION_REQUEST: string =
  "CREATE_CERTIFICATION_REQUEST";
export const CREATE_CERTIFICATION_SUCCESS: string =
  "CREATE_CERTIFICATION_SUCCESS";

//MY CERTIFICATION ACTIONS
export const SET_MY_CERTIFICATION_STATE: string = "SET_MY_CERTIFICATION_STATE";
export const RESET_MY_CERTIFICATION_STATE: string =
  "RESET_MY_CERTIFICATION_STATE";

export const FETCH_ALL_MY_CERTIFICATIONS_REQUEST: string =
  "FETCH_ALL_MY_CERTIFICATIONS_REQUEST";
export const FETCH_ALL_MY_CERTIFICATIONS_SUCCESS: string =
  "FETCH_ALL_MY_CERTIFICATIONS_SUCCESS";
export const MY_CERTIFICATION_FAILURE: string = "MY_CERTIFICATION_FAILURE";

//MODAL ACTIONS
export const SET_MODAL_STATE: string = "RESET_MODAL_STATE";
export const RESET_MODAL_STATE: string = "RESET_MODAL_STATE";
