//CONFIG ACTIONS
export const RESET_CONFIG_STATE: string = "RESET_CONFIG_STATE";
export const CERTIFIER_LOGIN: string = "CERTIFIER_LOGIN";
export const CLIENT_LOGIN: string = "CLIENT_LOGIN";

//NFT ACTIONS
export const SET_NFT_STATE: string = "SET_NFT_STATE";
export const RESET_NFT_STATE: string = "RESET_NFT_STATE";

export const FETCH_NFT_REQUEST = "FETCH_NFT_REQUEST";
export const FETCH_NFT_SUCCESS = "FETCH_NFT_SUCCESS";
export const NFT_FAILURE = "NFT_FAILURE";

export const FETCH_ALL_NFTS_REQUEST = "FETCH_ALL_NFTS_REQUEST";
export const FETCH_ALL_NFTS_SUCCESS = "FETCH_ALL_NFTS_SUCCESS";

export const FETCH_AVAILABLE_NFTS_REQUEST = "FETCH_AVAILABLE_NFTS_REQUEST";
export const FETCH_AVAILABLE_NFTS_SUCCESS = "FETCH_AVAILABLE_NFTS_SUCCESS";

export const CREATE_NFT_REQUEST = "CREATE_NFT_REQUEST";
export const CREATE_NFT_SUCCESS = "CREATE_NFT_SUCCESS";

//CERTIFICATION ACTIONS
export const SET_CERTIFICATION_STATE: string = "SET_CERTIFICATION_STATE";
export const RESET_CERTIFICATION_STATE: string = "RESET_CERTIFICATION_STATE";

export const FETCH_CERTIFICATION_REQUEST = "FETCH_CERTIFICATION_REQUEST";
export const FETCH_CERTIFICATION_SUCCESS = "FETCH_CERTIFICATION_SUCCESS";
export const CERTIFICATION_FAILURE = "CERTIFICATION_FAILURE";

export const FETCH_ALL_CERTIFICATIONS_REQUEST =
  "FETCH_ALL_CERTIFICATIONS_REQUEST";
export const FETCH_ALL_CERTIFICATIONS_SUCCESS =
  "FETCH_ALL_CERTIFICATIONS_SUCCESS";

export const CREATE_CERTIFICATION_REQUEST = "CREATE_CERTIFICATION_REQUEST";
export const CREATE_CERTIFICATION_SUCCESS = "CREATE_CERTIFICATION_SUCCESS";

//MODAL ACTIONS
export const SET_MODAL_STATE = "RESET_MODAL_STATE";
export const RESET_MODAL_STATE = "RESET_MODAL_STATE";
